# Lab5. Retriving the user Linkedin profile and analysing the profiles

###### NAME: RAJASREE S

###### ROLL NO: 215229147

### Profile Analysis

In [3]:
import os
import csv
import numpy as np

# Point this to your 'Connections.csv' file.
CSV_FILE = os.path.join('resources', 'ch04-linkedin', 'Connections.csv')

csvReader = csv.DictReader(open("Connections.csv"), delimiter=',', quotechar='"')
contacts = [row for row in csvReader]

### Simple normalization of company suffixes from address book data

In [6]:
from prettytable import PrettyTable # pip install prettytable
from collections import Counter
from operator import itemgetter

# Define a set of transforms that converts the first item
# to the second item. Here, we're simply handling some
# commonly known abbreviations, stripping off common suffixes, 
# etc.

transforms = [(', Inc.', ''), (', Inc', ''), (', LLC', ''), (', LLP', ''),
               (' LLC', ''), (' Inc.', ''), (' Inc', '')]

companies = [c['Company'].strip() for c in contacts if c['Company'].strip() != '']

for i, _ in enumerate(companies):
    for transform in transforms:
        companies[i] = companies[i].replace(*transform)

pt = PrettyTable(field_names=['Company', 'Freq'])
pt.align = 'l'
c = Counter(companies)

[pt.add_row([company, freq]) for (company, freq) in sorted(c.items(), key=itemgetter(1), reverse=True) if freq > 1]

print(pt)

+--------------------------------------------------+------+
| Company                                          | Freq |
+--------------------------------------------------+------+
| Bishop Heber College, Tiruchirappalli - 620 017. | 5    |
| MENMOZHI TECHNOLOGIES                            | 2    |
+--------------------------------------------------+------+

### Standardizing common job titles and computing their frequencies

In [7]:
transforms = [
    ('Sr.', 'Senior'),
    ('Sr', 'Senior'),
    ('Jr.', 'Junior'),
    ('Jr', 'Junior'),
    ('CEO', 'Chief Executive Officer'),
    ('COO', 'Chief Operating Officer'),
    ('CTO', 'Chief Technology Officer'),
    ('CFO', 'Chief Finance Officer'),
    ('VP', 'Vice President'),
    ]

# Read in a list of titles and split apart
# any combined titles like "President/CEO."
# Other variations could be handled as well, such
# as "President & CEO", "President and CEO", etc.

titles = []
for contact in contacts:
    titles.extend([t.strip() for t in contact['Position'].split('/')
                  if contact['Position'].strip() != ''])

# Replace common/known abbreviations

for i, _ in enumerate(titles):
    for transform in transforms:
        titles[i] = titles[i].replace(*transform)

# Print out a table of titles sorted by frequency

pt = PrettyTable(field_names=['Job Title', 'Freq'])
pt.align = 'l'
c = Counter(titles)
[pt.add_row([title, freq]) 
 for (title, freq) in sorted(c.items(), key=itemgetter(1), reverse=True) 
     if freq > 1]
print(pt)

# Print out a table of tokens sorted by frequency

tokens = []
for title in titles:
    tokens.extend([t.strip(',') for t in title.split()])
pt = PrettyTable(field_names=['Token', 'Freq'])
pt.align = 'l'
c = Counter(tokens)
[pt.add_row([token, freq]) 
 for (token, freq) in sorted(c.items(), key=itemgetter(1), reverse=True) 
     if freq > 1 and len(token) > 2]
print(pt)

+----------------+------+
| Job Title      | Freq |
+----------------+------+
| Data Analyst   | 2    |
| Data Scientist | 2    |
| Guest Lecturer | 2    |
+----------------+------+
+-----------+------+
| Token     | Freq |
+-----------+------+
| Data      | 5    |
| Intern    | 3    |
| Analyst   | 2    |
| Student   | 2    |
| Associate | 2    |
| Scientist | 2    |
| Guest     | 2    |
| Lecturer  | 2    |
+-----------+------+

### Geocoding locations with Google Maps

**Note:** This section contains no locations bcoz there is no geocode generated

In [4]:
for i, c in enumerate(contacts):
    progress = '{0:3d} of {1:3d} - '.format(i+1,len(contacts))
    company = c['Company']
    try:
        location = g.geocode(company, exactly_one=True)
    except:
        print('... Failed to get a location for {0}'.format(company))
        location = None
    
    if location != None:
        c.update([('Location', location)])
        print(progress + company[:50] + ' -- ' + location.address)
    else:
        c.update([('Location', None)])
        print(progress + company[:50] + ' -- ' + 'Unknown Location')

... Failed to get a location for
  1 of  54 -  -- Unknown Location
... Failed to get a location for Synapse Business Systems Inc
  2 of  54 - Synapse Business Systems Inc  -- Unknown Location
... Failed to get a location for
  3 of  54 -  -- Unknown Location
... Failed to get a location for Vagus Technologies
  4 of  54 - Vagus Technologies -- Unknown Location
... Failed to get a location for
  5 of  54 -  -- Unknown Location
... Failed to get a location for Mila - Quebec Artificial Intelligence Institute
  6 of  54 - Mila - Quebec Artificial Intelligence Institute -- Unknown Location
... Failed to get a location for
  7 of  54 -  -- Unknown Location
... Failed to get a location for Bishop Heber College, Trichy
  8 of  54 - Bishop Heber College, Trichy -- Unknown Location
... Failed to get a location for
  9 of  54 -  -- Unknown Location
... Failed to get a location for
 10 of  54 -  -- Unknown Location
... Failed to get a location for
 11 of  54 -  -- Unknown Location
... Failed to get a location for Bishop Heber College, Tiruchirappalli - 620 017.
 12 of  54 - Bishop Heber College, Tiruchirappalli - 620 017. -- Unknown Location
... Failed to get a location for MENMOZHI TECHNOLOGIES
 13 of  54 - MENMOZHI TECHNOLOGIES -- Unknown Location
... Failed to get a location for
 14 of  54 -  -- Unknown Location
... Failed to get a location for
 15 of  54 -  -- Unknown Location
... Failed to get a location for Chegg Inc.
 16 of  54 - Chegg Inc. -- Unknown Location
... Failed to get a location for
 17 of  54 -  -- Unknown Location
... Failed to get a location for
 18 of  54 -  -- Unknown Location
... Failed to get a location for
 19 of  54 -  -- Unknown Location
... Failed to get a location for Tech Mahindra
 20 of  54 - Tech Mahindra -- Unknown Location
... Failed to get a location for
 21 of  54 -  -- Unknown Location
... Failed to get a location for
 22 of  54 -  -- Unknown Location
... Failed to get a location for
 23 of  54 -  -- Unknown Location
... Failed to get a location for Learn and Build
 24 of  54 - Learn and Build -- Unknown Location
... Failed to get a location for
 25 of  54 -  -- Unknown Location
... Failed to get a location for
 26 of  54 -  -- Unknown Location
... Failed to get a location for
 27 of  54 -  -- Unknown Location
... Failed to get a location for
 28 of  54 -  -- Unknown Location
... Failed to get a location for
 29 of  54 -  -- Unknown Location
... Failed to get a location for
 30 of  54 -  -- Unknown Location
... Failed to get a location for
 31 of  54 -  -- Unknown Location
... Failed to get a location for
 32 of  54 -  -- Unknown Location
... Failed to get a location for Bishop Heber College, Tiruchirappalli - 620 017.
 33 of  54 - Bishop Heber College, Tiruchirappalli - 620 017. -- Unknown Location
... Failed to get a location for
 34 of  54 -  -- Unknown Location
... Failed to get a location for
 35 of  54 -  -- Unknown Location
... Failed to get a location for Bishop Heber College, Tiruchirappalli - 620 017.
 36 of  54 - Bishop Heber College, Tiruchirappalli - 620 017. -- Unknown Location
... Failed to get a location for
 37 of  54 -  -- Unknown Location
... Failed to get a location for
 38 of  54 -  -- Unknown Location
... Failed to get a location for Kissflow
 39 of  54 - Kissflow -- Unknown Location
... Failed to get a location for Actify Data Labs
 40 of  54 - Actify Data Labs -- Unknown Location
... Failed to get a location for
 41 of  54 -  -- Unknown Location
... Failed to get a location for
 42 of  54 -  -- Unknown Location
... Failed to get a location for Bishop Heber College, Tiruchirappalli - 620 017.
 43 of  54 - Bishop Heber College, Tiruchirappalli - 620 017. -- Unknown Location
... Failed to get a location for
 44 of  54 -  -- Unknown Location
... Failed to get a location for
 45 of  54 -  -- Unknown Location
... Failed to get a location for Bishop Heber College, Tiruchirappalli - 620 017.
 46 of  54 - Bishop Heber College, Tiruchirappalli - 620 017. -- Unknown Location
... Failed to get a location for KPMG India
 47 of  54 - KPMG India -- Unknown Location
... Failed to get a location for Bishop Heber College, Tiruchirappalli - 620 017.
 48 of  54 - Bishop Heber College, Tiruchirappalli - 620 017. -- Unknown Location
... Failed to get a location for
 49 of  54 -  -- Unknown Location
... Failed to get a location for
 50 of  54 -  -- Unknown Location
... Failed to get a location for
 51 of  54 -  -- Unknown Location
... Failed to get a location for
 52 of  54 -  -- Unknown Location
... Failed to get a location for Genpact
 53 of  54 - Genpact -- Unknown Location
... Failed to get a location for MENMOZHI TECHNOLOGIES
 54 of  54 - MENMOZHI TECHNOLOGIES -- Unknown Location

SMA lab 06 clustering the job titles of Linkedin

#**Clustering job titles using a greedy heuristic**

In [8]:
from nltk.util import bigrams

ceo_bigrams = list(bigrams("Chief Executive Officer".split(), pad_left=True, pad_right=True))
cto_bigrams = list(bigrams("Chief Technology Officer".split(), pad_left=True, pad_right=True))

print(ceo_bigrams)
print(cto_bigrams)

print(len(set(ceo_bigrams).intersection(set(cto_bigrams))))

[(None, 'Chief'), ('Chief', 'Executive'), ('Executive', 'Officer'), ('Officer', None)]
[(None, 'Chief'), ('Chief', 'Technology'), ('Technology', 'Officer'), ('Officer', None)]
2

###Jaccard distance calculation

In [9]:
from nltk.metrics.distance import jaccard_distance # pip install nltk

job_title_1 = 'Chief Executive Officer'.split()
job_title_2 = 'Chief Technology Officer'.split()

print(job_title_1)
print(job_title_2)

print()
print('Intersection:')
intersection = set(job_title_1).intersection(set(job_title_2))
print(intersection)

print()
print('Union:')
union = set(job_title_1).union(set(job_title_2))
print(union)

print()
print('Similarity:', len(intersection) / len(union))
print('Distance:', jaccard_distance(set(job_title_1), set(job_title_2)))

['Chief', 'Executive', 'Officer']
['Chief', 'Technology', 'Officer']

Intersection:
{'Chief', 'Officer'}

Union:
{'Chief', 'Officer', 'Technology', 'Executive'}

Similarity: 0.5
Distance: 0.5

In [10]:
job_title_1 = 'Vice President, Sales'.split()
job_title_2 = 'Vice President, Customer Relations'.split()

print(job_title_1)
print(job_title_2)

print()
print('Intersection:')
intersection = set(job_title_1).intersection(set(job_title_2))
print(intersection)

print()
print('Union:')
union = set(job_title_1).union(set(job_title_2))
print(union)

print()
print('Similarity:', len(intersection) / len(union))
print('Distance:', jaccard_distance(set(job_title_1), set(job_title_2)))

['Vice', 'President,', 'Sales']
['Vice', 'President,', 'Customer', 'Relations']

Intersection:
{'Vice', 'President,'}

Union:
{'Vice', 'Sales', 'Relations', 'Customer', 'President,'}

Similarity: 0.4
Distance: 0.6

In [19]:
contacts

[{'First Name': 'ARAVINTHAN',
  'Last Name': 'K',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '06-Aug-22'},
 {'First Name': 'Abisheik',
  'Last Name': 'M',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '06-Aug-22'},
 {'First Name': 'Rahul',
  'Last Name': 'Venkat S',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '06-Aug-22'},
 {'First Name': 'Arzoo',
  'Last Name': 'Sah',
  'Email Address': '',
  'Company': 'The Sparks Foundation',
  'Position': 'Computer Vision & IoT Intern',
  'Connected On': '13-Jul-22'},
 {'First Name': 'Bharathwin',
  'Last Name': 'MA',
  'Email Address': '',
  'Company': 'KPMG India',
  'Position': 'Data Analytics consulting Virtual Internship',
  'Connected On': '12-Jul-22'},
 {'First Name': 'C R',
  'Last Name': 'LAKSHMI',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '16-Jun-22'},
 {'First Name': 'Yokeshwaran ',
  'Last Name': 'G',
  'Email Address': '',
  'Company': 'Learn and Build',
  'Position': 'Summer Intern',
  'Connected On': '12-May-22'},
 {'First Name': 'Dhivyadharshni',
  'Last Name': 'Natarajan',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Mar-22'},
 {'First Name': 'Sherine',
  'Last Name': 'Raymon Johns',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Mar-22'},
 {'First Name': 'DHANAPRIYA',
  'Last Name': 'A',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Mar-22'},
 {'First Name': 'Aravinth',
  'Last Name': 'Aravinth',
  'Email Address': '',
  'Company': 'Amazon',
  'Position': 'Data Analyst',
  'Connected On': '30-Mar-22'},
 {'First Name': 'ARUN',
  'Last Name': 'KUMAR M',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Mar-22'},
 {'First Name': 'Kirubha',
  'Last Name': 'Karan',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Mar-22'},
 {'First Name': 'Arjun',
  'Last Name': 'V S',
  'Email Address': '',
  'Company': 'Mila - Quebec Artificial Intelligence Institute',
  'Position': 'Student Researcher',
  'Connected On': '11-Mar-22'},
 {'First Name': 'Hariharasudhan',
  'Last Name': 'D',
  'Email Address': '',
  'Company': 'MENMOZHI TECHNOLOGIES',
  'Position': 'Intern',
  'Connected On': '29-Dec-21'},
 {'First Name': 'Arunachalam',
  'Last Name': 'S',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '29-Dec-21'},
 {'First Name': 'Rajesh',
  'Last Name': 'Kannan M',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '25-Nov-21'},
 {'First Name': 'Jo-Anna',
  'Last Name': 'Elizabeth J',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '25-Nov-21'},
 {'First Name': 'Rithik',
  'Last Name': 'R',
  'Email Address': '',
  'Company': 'Tech Mahindra',
  'Position': 'Business Associate',
  'Connected On': '25-Nov-21'},
 {'First Name': 'Divya',
  'Last Name': 'Duraisamy',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '21-Nov-21'},
 {'First Name': 'Arunkumar',
  'Last Name': 'A',
  'Email Address': '',
  'Company': 'MENMOZHI TECHNOLOGIES',
  'Position': 'Data Scientist',
  'Connected On': '18-Nov-21'},
 {'First Name': 'Kausalya',
  'Last Name': 'Sivakumar',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '12-Nov-21'},
 {'First Name': 'Kelvin',
  'Last Name': 'Christober',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '08-Nov-21'},
 {'First Name': 'kavinilavu',
  'Last Name': 'elangovan',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '08-Nov-21'},
 {'First Name': 'Deepika',
  'Last Name': 'Murugan',
  'Email Address': '',
  'Company': 'Bishop Heber College, Tiruchirappalli - 620 017.',
  'Position': 'Data Scientist',
  'Connected On': '30-Oct-21'},
 {'First Name': 'E',
  'Last Name': 'Sundar',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Oct-21'},
 {'First Name': 'Berchmans',
  'Last Name': 'Kevin S',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '27-Oct-21'},
 {'First Name': 'SAMIDURAI',
  'Last Name': 'S',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '27-Oct-21'},
 {'First Name': 'Swathi',
  'Last Name': 'Santhanam',
  'Email Address': '',
  'Company': 'Superprof',
  'Position': 'Online Tutor',
  'Connected On': '24-Oct-21'},
 {'First Name': 'Rexson',
  'Last Name': 'Epiron',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '24-Oct-21'},
 {'First Name': 'Sujith',
  'Last Name': 'R',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '23-Oct-21'},
 {'First Name': 'SHARON',
  'Last Name': 'SAM S',
  'Email Address': '',
  'Company': 'Bishop Heber College, Tiruchirappalli - 620 017.',
  'Position': 'Student',
  'Connected On': '23-Oct-21'},
 {'First Name': 'Vasavi',
  'Last Name': 'R',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '23-Oct-21'},
 {'First Name': 'Jayasurya',
  'Last Name': 'V',
  'Email Address': '',
  'Company': 'Actify Data Labs',
  'Position': 'Data Analyst',
  'Connected On': '23-Oct-21'},
 {'First Name': 'Dr.B.GAYATHRI',
  'Last Name': 'MCA.,M.Phil.,Ph.D',
  'Email Address': '',
  'Company': 'Bishop Heber College, Tiruchirappalli - 620 017.',
  'Position': 'Associate Professor',
  'Connected On': '22-Oct-21'},
 {'First Name': 'Nambirajan',
  'Last Name': 'R S',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'Sujitha',
  'Last Name': 'Rajasekaran',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'Janani',
  'Last Name': 'Selvaraj PhD',
  'Email Address': '',
  'Company': 'Bishop Heber College, Tiruchirappalli - 620 017.',
  'Position': 'Guest Lecturer',
  'Connected On': '22-Oct-21'},
 {'First Name': 'Bharat',
  'Last Name': 'V',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'Ajithra',
  'Last Name': 'P',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'Ashika',
  'Last Name': 'Devi',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'Jemimah',
  'Last Name': 'Kandaraj',
  'Email Address': '',
  'Company': 'Bishop Heber College, Tiruchirappalli - 620 017.',
  'Position': 'Guest Lecturer',
  'Connected On': '22-Oct-21'},
 {'First Name': 'ABISHEK',
  'Last Name': 'N',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'ranjani',
  'Last Name': 'balasubramanian',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'}]

In [12]:
import json
# Tweak this distance threshold and try different distance calculations 
# during experimentation
DISTANCE_THRESHOLD = 0.6
DISTANCE = jaccard_distance



def cluster_contacts_by_title():

    transforms = [
        ('Sr.', 'Senior'),
        ('Sr', 'Senior'),
        ('Jr.', 'Junior'),
        ('Jr', 'Junior'),
        ('CEO', 'Chief Executive Officer'),
        ('COO', 'Chief Operating Officer'),
        ('CTO', 'Chief Technology Officer'),
        ('CFO', 'Chief Finance Officer'),
        ('VP', 'Vice President'),
        ]

    separators = ['/', ' and ', ' & ', '|', ',']

    # Normalize and/or replace known abbreviations
    # and build up a list of common titles.

    all_titles = []
    for i, _ in enumerate(contacts):
        if contacts[i]['Position'] == '':
            contacts[i]['Position'] = ['']
            continue
        titles = [contacts[i]['Position']]
        
        all_titles.extend(titles)

    all_titles = list(set(all_titles))

    clusters = {}
    for title1 in all_titles:
        clusters[title1] = []
        for title2 in all_titles:
            if title2 in clusters[title1] or title2 in clusters and title1 \
                in clusters[title2]:
                continue
            try:
                distance = DISTANCE(set(title1.split()), set(title2.split()))
            except:
                print(title1.split())
                print(title2.split())
                continue

            if distance < DISTANCE_THRESHOLD:
                clusters[title1].append(title2)

    # Flatten out clusters
    clusters = [clusters[title] for title in clusters if len(clusters[title]) > 1]

    # Round up contacts who are in these clusters and group them together
    clustered_contacts = {}
    for cluster in clusters:
        clustered_contacts[tuple(cluster)] = []
        for contact in contacts:
            for title in contact['Position']:
                if title in cluster:
                    clustered_contacts[tuple(cluster)].append('{0} {1}.'.format(
                        contact['FirstName'], contact['LastName'][0]))

    return clustered_contacts


clustered_contacts = cluster_contacts_by_title()

for titles in clustered_contacts:
    common_titles_heading = 'Common Titles: ' + ', '.join(titles)

    descriptive_terms = set(titles[0].split())
    for title in titles:
        descriptive_terms.intersection_update(set(title.split()))
    if len(descriptive_terms) == 0: descriptive_terms = ['***No words in common***']
    descriptive_terms_heading = 'Descriptive Terms: ' \
        + ', '.join(descriptive_terms)
    print(common_titles_heading)
    print('\n'+descriptive_terms_heading)
    print('-' * 70)
    print('\n'.join(clustered_contacts[titles]))
    print()

Common Titles: Student Researcher, Student

Descriptive Terms: Student
----------------------------------------------------------------------


Common Titles: Intern, Summer Intern

Descriptive Terms: Intern
----------------------------------------------------------------------

###How to export data to power a dendogram and node-link tree visualization

In [13]:
pip install cluster

Collecting clusterNote: you may need to restart the kernel to use updated packages.
  Downloading cluster-1.4.1.post3-py2.py3-none-any.whl (28 kB)
Installing collected packages: cluster
Successfully installed cluster-1.4.1.post3

In [14]:
import cluster

In [15]:
contacts

[{'First Name': 'ARAVINTHAN',
  'Last Name': 'K',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '06-Aug-22'},
 {'First Name': 'Abisheik',
  'Last Name': 'M',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '06-Aug-22'},
 {'First Name': 'Rahul',
  'Last Name': 'Venkat S',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '06-Aug-22'},
 {'First Name': 'Arzoo',
  'Last Name': 'Sah',
  'Email Address': '',
  'Company': 'The Sparks Foundation',
  'Position': 'Computer Vision & IoT Intern',
  'Connected On': '13-Jul-22'},
 {'First Name': 'Bharathwin',
  'Last Name': 'MA',
  'Email Address': '',
  'Company': 'KPMG India',
  'Position': 'Data Analytics consulting Virtual Internship',
  'Connected On': '12-Jul-22'},
 {'First Name': 'C R',
  'Last Name': 'LAKSHMI',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '16-Jun-22'},
 {'First Name': 'Yokeshwaran ',
  'Last Name': 'G',
  'Email Address': '',
  'Company': 'Learn and Build',
  'Position': 'Summer Intern',
  'Connected On': '12-May-22'},
 {'First Name': 'Dhivyadharshni',
  'Last Name': 'Natarajan',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Mar-22'},
 {'First Name': 'Sherine',
  'Last Name': 'Raymon Johns',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Mar-22'},
 {'First Name': 'DHANAPRIYA',
  'Last Name': 'A',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Mar-22'},
 {'First Name': 'Aravinth',
  'Last Name': 'Aravinth',
  'Email Address': '',
  'Company': 'Amazon',
  'Position': 'Data Analyst',
  'Connected On': '30-Mar-22'},
 {'First Name': 'ARUN',
  'Last Name': 'KUMAR M',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Mar-22'},
 {'First Name': 'Kirubha',
  'Last Name': 'Karan',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Mar-22'},
 {'First Name': 'Arjun',
  'Last Name': 'V S',
  'Email Address': '',
  'Company': 'Mila - Quebec Artificial Intelligence Institute',
  'Position': 'Student Researcher',
  'Connected On': '11-Mar-22'},
 {'First Name': 'Hariharasudhan',
  'Last Name': 'D',
  'Email Address': '',
  'Company': 'MENMOZHI TECHNOLOGIES',
  'Position': 'Intern',
  'Connected On': '29-Dec-21'},
 {'First Name': 'Arunachalam',
  'Last Name': 'S',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '29-Dec-21'},
 {'First Name': 'Rajesh',
  'Last Name': 'Kannan M',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '25-Nov-21'},
 {'First Name': 'Jo-Anna',
  'Last Name': 'Elizabeth J',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '25-Nov-21'},
 {'First Name': 'Rithik',
  'Last Name': 'R',
  'Email Address': '',
  'Company': 'Tech Mahindra',
  'Position': 'Business Associate',
  'Connected On': '25-Nov-21'},
 {'First Name': 'Divya',
  'Last Name': 'Duraisamy',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '21-Nov-21'},
 {'First Name': 'Arunkumar',
  'Last Name': 'A',
  'Email Address': '',
  'Company': 'MENMOZHI TECHNOLOGIES',
  'Position': 'Data Scientist',
  'Connected On': '18-Nov-21'},
 {'First Name': 'Kausalya',
  'Last Name': 'Sivakumar',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '12-Nov-21'},
 {'First Name': 'Kelvin',
  'Last Name': 'Christober',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '08-Nov-21'},
 {'First Name': 'kavinilavu',
  'Last Name': 'elangovan',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '08-Nov-21'},
 {'First Name': 'Deepika',
  'Last Name': 'Murugan',
  'Email Address': '',
  'Company': 'Bishop Heber College, Tiruchirappalli - 620 017.',
  'Position': 'Data Scientist',
  'Connected On': '30-Oct-21'},
 {'First Name': 'E',
  'Last Name': 'Sundar',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '30-Oct-21'},
 {'First Name': 'Berchmans',
  'Last Name': 'Kevin S',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '27-Oct-21'},
 {'First Name': 'SAMIDURAI',
  'Last Name': 'S',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '27-Oct-21'},
 {'First Name': 'Swathi',
  'Last Name': 'Santhanam',
  'Email Address': '',
  'Company': 'Superprof',
  'Position': 'Online Tutor',
  'Connected On': '24-Oct-21'},
 {'First Name': 'Rexson',
  'Last Name': 'Epiron',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '24-Oct-21'},
 {'First Name': 'Sujith',
  'Last Name': 'R',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '23-Oct-21'},
 {'First Name': 'SHARON',
  'Last Name': 'SAM S',
  'Email Address': '',
  'Company': 'Bishop Heber College, Tiruchirappalli - 620 017.',
  'Position': 'Student',
  'Connected On': '23-Oct-21'},
 {'First Name': 'Vasavi',
  'Last Name': 'R',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '23-Oct-21'},
 {'First Name': 'Jayasurya',
  'Last Name': 'V',
  'Email Address': '',
  'Company': 'Actify Data Labs',
  'Position': 'Data Analyst',
  'Connected On': '23-Oct-21'},
 {'First Name': 'Dr.B.GAYATHRI',
  'Last Name': 'MCA.,M.Phil.,Ph.D',
  'Email Address': '',
  'Company': 'Bishop Heber College, Tiruchirappalli - 620 017.',
  'Position': 'Associate Professor',
  'Connected On': '22-Oct-21'},
 {'First Name': 'Nambirajan',
  'Last Name': 'R S',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'Sujitha',
  'Last Name': 'Rajasekaran',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'Janani',
  'Last Name': 'Selvaraj PhD',
  'Email Address': '',
  'Company': 'Bishop Heber College, Tiruchirappalli - 620 017.',
  'Position': 'Guest Lecturer',
  'Connected On': '22-Oct-21'},
 {'First Name': 'Bharat',
  'Last Name': 'V',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'Ajithra',
  'Last Name': 'P',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'Ashika',
  'Last Name': 'Devi',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'Jemimah',
  'Last Name': 'Kandaraj',
  'Email Address': '',
  'Company': 'Bishop Heber College, Tiruchirappalli - 620 017.',
  'Position': 'Guest Lecturer',
  'Connected On': '22-Oct-21'},
 {'First Name': 'ABISHEK',
  'Last Name': 'N',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'},
 {'First Name': 'ranjani',
  'Last Name': 'balasubramanian',
  'Email Address': '',
  'Company': '',
  'Position': [''],
  'Connected On': '22-Oct-21'}]

In [16]:
import nltk
nltk.download('stopwords')
from nltk.metrics.distance import jaccard_distance
from nltk.corpus import stopwords # nltk.download('stopwords')
from cluster import HierarchicalClustering # pip install cluster
import os
CSV_FILE = os.path.join('Connections.csv')

# Tweak this distance threshold and try different distance calculations 
# during experimentation
DISTANCE_THRESHOLD = 0.5
DISTANCE = jaccard_distance

# Adjust sample size as needed to reduce the runtime of the
# nested loop that invokes the DISTANCE function
SAMPLE_SIZE = 500

def cluster_contacts_by_title(csv_file):

    csvReader = csv.DictReader(open(csv_file), delimiter=',', quotechar='"')
    contacts = [row for row in csvReader]
    contacts = contacts[:SAMPLE_SIZE]
    
    transforms = [
        ('Sr.', 'Senior'),
        ('Sr', 'Senior'),
        ('Jr.', 'Junior'),
        ('Jr', 'Junior'),
        ('CEO', 'Chief Executive Officer'),
        ('COO', 'Chief Operating Officer'),
        ('CTO', 'Chief Technology Officer'),
        ('CFO', 'Chief Finance Officer'),
        ('VP', 'Vice President'),
        ]

    separators = ['/', ' and ', '|', ',', ' & ']

    # Normalize and/or replace known abbreviations
    # and build up a list of common titles.

    all_titles = []
    for i, _ in enumerate(contacts):
        if contacts[i]['Position'] == '':
            contacts[i]['Position'] = ['']
            continue
        titles = [contacts[i]['Position']]
        for separator in separators:
            for title in titles:
                if title.find(separator) >= 0:
                    titles.remove(title)
                    titles.extend([title.strip() for title in title.split(separator) if title.strip() != ''])

        for transform in transforms:
            titles = [title.replace(*transform) for title in titles]
            
        contacts[i]['Position'] = titles
        all_titles.extend(titles)

    all_titles = list(set(all_titles))
    
    # Define a scoring function
    def score(title1, title2): 
        return DISTANCE(set(title1.split()), set(title2.split()))

    # Feed the class your data and the scoring function
    hc = HierarchicalClustering(all_titles, score)

    # Cluster the data according to a distance threshold
    clusters = hc.getlevel(DISTANCE_THRESHOLD)

    # Remove singleton clusters
    clusters = [c for c in clusters if len(c) > 1]

    # Round up contacts who are in these clusters and group them together
    clustered_contacts = {}
    for cluster in clusters:
        clustered_contacts[tuple(cluster)] = []
        for contact in contacts:
            for title in contact['Position']:
                if title in cluster:
                    clustered_contacts[tuple(cluster)].append('{0} {1}.'.format(
                        contact['First Name'], contact['Last Name'][0]))

    return clustered_contacts, clusters

def get_descriptive_terms(titles):
    flatten = lambda l: [item for sublist in l for item in sublist]
    title_words = flatten([title.split() for title in titles])
    filtered_words = [word for word in title_words \
                      if word not in stopwords.words('english')]
    counter = Counter(filtered_words)
    descriptive_terms = counter.most_common(2)
    # Get the most common title words from a cluster, ignoring singletons
    descriptive_terms = [t[0] for t in descriptive_terms if t[1] > 1]
    return descriptive_terms


def display_output(clustered_contacts, clusters):    
    for title_cluster in clusters:
        descriptive_terms = get_descriptive_terms(title_cluster)
        common_titles_heading = 'Common Titles: ' + ', '.join((t for t in title_cluster))
        descriptive_terms_heading =  'Descriptive Terms: ' + ', '.join((t for t in descriptive_terms))
        
        print(common_titles_heading)
        print(descriptive_terms_heading)
        print('-' * 70)
        #print(title_cluster)
        #print(clustered_contacts)
        print('\n'.join(clustered_contacts[tuple(title_cluster)]))
        print()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\S.Saravanan\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [17]:
clustered_contacts

{('Student Researcher', 'Student'): [], ('Intern', 'Summer Intern'): []}

In [20]:
def write_d3_json_output(clustered_contacts):
    
    json_output = {'name' : 'My LinkedIn', 'children' : []}

    for titles in clustered_contacts:

        descriptive_terms = get_descriptive_terms(titles)

        json_output['children'].append({'name' : ', '.join(descriptive_terms)[:30], 'children' : [ {'name' : c} for c in clustered_contacts[titles] ] } )
        with open("sample.json", "w") as out_file:
            json.dump(json_output,out_file,indent=1)
            out_file.close()
    
clustered_contacts, clusters = cluster_contacts_by_title(CSV_FILE)
display_output(clustered_contacts, clusters)
write_d3_json_output(clustered_contacts)

Common Titles: Student, Student Researcher
Descriptive Terms: Student
----------------------------------------------------------------------
Arjun V.
SHARON S.

Common Titles: Summer Intern, Intern, IoT Intern
Descriptive Terms: Intern
----------------------------------------------------------------------
Arzoo S.
Yokeshwaran  G.
Hariharasudhan D.